import{a as y,S as L,i}from"./assets/vendor-tnUJPedx.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const d of o.addedNodes)d.tagName==="LINK"&&d.rel==="modulepreload"&&s(d)}).observe(document,{childList:!0,subtree:!0});function n(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function s(e){if(e.ep)return;e.ep=!0;const o=n(e);fetch(e.href,o)}})();const w="47392920-efce9c2b3427e3353db7767ab",b="https://pixabay.com/api/",$=15;async function g(t,r=1){const n=`${b}?key=${w}&q=${t}&image_type=photo&orientation=horizontal&safesearch=true&per_page=${$}&page=${r}`;try{const s=await y.get(n);if(s.data.hits.length===0)throw new Error("No images found");return s.data}catch(s){throw console.error("Error fetching images:",s),s}}function E(t){t.innerHTML=""}function m(t,r,n){const s=t.map(e=>`
        <a href="${e.largeImageURL}" class="gallery-link">
          <div class="card">
            <img src="${e.webformatURL}" alt="${e.tags}" loading="lazy" />
            <div class="card-info">
              <span>Likes: ${e.likes}</span>
              <span>Views: ${e.views}</span>
              <span>Comments: ${e.comments}</span>
              <span>Downloads: ${e.downloads}</span>
            </div>
          </div>
        </a>`).join("");r.insertAdjacentHTML("beforeend",s),n.refresh()}const v=document.querySelector("#search-form"),l=document.querySelector(".gallery"),h=document.querySelector("#load-more"),S=document.querySelector("#loader");let p=new L(".gallery a"),c="",a=1;v.addEventListener("submit",P);h.addEventListener("click",q);async function P(t){if(t.preventDefault(),c=t.currentTarget.searchQuery.value.trim(),!c){i.warning({title:"Warning",message:"Please enter a search query!"});return}a=1,E(l),u(!1);try{const{hits:r,totalHits:n}=await g(c,a);m(r,l,p),i.success({title:"Success",message:`Found ${n} images!`}),n>a*15&&u(!0)}catch(r){i.error({title:"Error",message:r.message})}}async function q(){a+=1,f(!0);try{const{hits:t,totalHits:r}=await g(c,a);m(t,l,p),a*15>=r&&u(!1),M()}catch{i.error({title:"Error",message:"Failed to load more images."})}finally{f(!1)}}function u(t){h.classList.toggle("hidden",!t)}function f(t){S.classList.toggle("hidden",!t)}function M(){const{height:t}=l.firstElementChild.getBoundingClientRect();window.scrollBy({top:t*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
